### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by stricktech** [ohaidan/QBCore-Admin-Panel#1]
Hey. I'm super interested in this. Will be switching my server to qbcore tonight and would like to purchase this asap. Can you please reply with your dicord link? The one linked is not working
![Screenshot_20220211-165249_Chrome](https://user-images.githubusercontent.com/50678364/153681604-7029c040-7a14-4700-9ede-81e9032e6877.jpg)

**Comment by ohaidan** [comment]
https://discord.iv-studios.net
